### ISSUE TITLE
fighters with 0 fights

### ISSUE THREAD

**Issue by ioannis12** [andrew-couch/UFC-Sports-Betting-Model#1]
hello, 

congrats for your work, I just had a look at the predictions file, I noticed you are predicting for fights where either or both fighters have 0 fights. How are you doing this, if there is no data for them?

greetings

**Comment by andrew-couch** [comment]
The features that are created use a variety of AR and MA terms but if there is no data (previous fights) the features are set to 0. The models were trained with the entire historical data so each fighter has a fight where there was no data but the outcome was known.

I assumed that the majority of fighters on the main card would have at least a few fights so I didn't add any flags that would indicate the predictions are unstable. However, I think the applicable package may actually be useful for solving this problem. I may update the models where I only use fights where a fighter has had at least a few fights but I want to first add a report/summary of model predictions for upcoming fights in the README.
